# Generated by Django 5.0.2 on 2024-03-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_remove_datasetentry_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasetentry',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='datasetentry',
            name='feedback',
        ),
        migrations.AddField(
            model_name='datasetentry',
            name='sentiment',
            field=models.TextField(default=''),
        ),
    ]
