# Generated by Django 5.0.2 on 2024-03-19 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_rename_text_datasetentry_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetentry',
            name='language',
        ),
        migrations.RemoveField(
            model_name='datasetentry',
            name='sentiment',
        ),
    ]
