# Generated by Django 5.0.2 on 2024-03-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_label_remove_datasetentry_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetentry',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
