# Generated by Django 5.0.2 on 2024-03-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_role_remove_datasetentry_roles_datasetentry_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetentry',
            name='roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddField(
            model_name='datasetentry',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
