# Generated by Django 5.0.2 on 2024-03-28 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_remove_datasetentry_roles_delete_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.conversation')),
                ('predicted_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.label')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='predicted_categories',
            field=models.ManyToManyField(through='assistant.PredictedCategory', to='assistant.label'),
        ),
    ]
