# Generated by Django 5.0.2 on 2024-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_predictedcategory_conversation_predicted_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datasetentry',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
