# Generated by Django 5.0.2 on 2024-04-11 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_supportticket_remove_message_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticket',
            old_name='subject',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='requester_email',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='status',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.supportticket'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
