# Generated by Django 5.0.2 on 2024-04-12 16:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='users_to_notify',
            field=models.ManyToManyField(blank=True, related_name='tickets_to_notify', to=settings.AUTH_USER_MODEL),
        ),
    ]
