# Generated by Django 5.0.2 on 2024-04-07 01:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='auth_user_details',
        ),
    ]
