# Generated by Django 5.0.2 on 2024-04-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_primaryinstrument_secondaryinstrument_teachingmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=50)),
                ('secondary_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PrimaryInstrument',
        ),
        migrations.DeleteModel(
            name='SecondaryInstrument',
        ),
    ]
