# Generated by Django 5.0.2 on 2024-04-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_alter_instrument_primary_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ManyToManyField(to='administrator.instrument')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.auth_user_details')),
                ('teachingmode', models.ManyToManyField(to='administrator.teachingmode')),
            ],
        ),
    ]
