# Generated by Django 5.0.2 on 2024-04-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teachingmode',
        ),
        migrations.AddField(
            model_name='teacher',
            name='instrument',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.instrument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachingmode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='administrator.teachingmode'),
            preserve_default=False,
        ),
    ]
