# Generated by Django 5.0.2 on 2024-04-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_teacher_instrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='primary_name',
            new_name='instrument_name',
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='secondary_name',
        ),
    ]
