# Generated by Django 5.0.2 on 2024-05-08 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_student_assigned_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instrument',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.instrument'),
        ),
        migrations.AddField(
            model_name='student',
            name='teaching_mode',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.teachingmode'),
        ),
    ]
