# Generated by Django 5.0.2 on 2024-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_student_assigned_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='identification_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
