# Generated by Django 5.0.2 on 2024-05-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_student_birthdate_student_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user_details',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
