# Generated by Django 5.0.2 on 2024-05-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_auth_user_details_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
    ]
