# Generated by Django 5.0.2 on 2024-05-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_bookinstrument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrument_name',
            new_name='instrument_major_name',
        ),
        migrations.AddField(
            model_name='instrument',
            name='instrument_minor_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
