# Generated by Django 5.0.2 on 2024-05-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_activity_album_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='activityID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.activity'),
        ),
    ]
