# Generated by Django 5.0.2 on 2024-05-26 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_moduledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.book'),
        ),
    ]
