# Generated by Django 5.0.2 on 2024-05-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0027_student_current_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_name',
            field=models.ImageField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
