# Generated by Django 5.0.2 on 2024-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_alter_media_media_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='albumID',
        ),
        migrations.AddField(
            model_name='media',
            name='albumID',
            field=models.ManyToManyField(to='administrator.album'),
        ),
    ]
