# Generated by Django 5.0.2 on 2024-05-30 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_remove_media_albumid_media_albumid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='albumID',
        ),
        migrations.AddField(
            model_name='media',
            name='albumID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.album'),
        ),
    ]
