# Generated by Django 5.0.2 on 2024-05-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0030_remove_media_albumid_media_albumid'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recurring_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
