# Generated by Django 5.0.2 on 2024-05-31 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_activity_recurring_weeks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='recurring_weeks',
        ),
    ]
