# Generated by Django 5.0.2 on 2024-06-18 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_rename_current_book_student_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teachingmode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.teachingmode'),
        ),
    ]
