# Generated by Django 5.0.2 on 2024-06-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0036_alter_teacher_teachingmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pictures/'),
        ),
    ]
