# Generated by Django 5.0.2 on 2024-06-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_remove_activity_recurring_weeks'),
        ('teacher', '0005_remove_attendance_attendance_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.teacher'),
            preserve_default=False,
        ),
    ]
