# Generated by Django 5.0.2 on 2024-06-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_attendance_teacher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='absence_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
