# Generated by Django 5.0.2 on 2024-06-13 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_attendance_absence_reason_attendance_absence_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absence_title',
        ),
    ]
