# Generated by Django 5.0.2 on 2024-06-15 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_attendance_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='teacher',
        ),
    ]
