# Generated by Django 5.0.2 on 2024-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_remove_attendance_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recurring_weeks',
            field=models.IntegerField(default=0),
        ),
    ]
