# Generated by Django 5.0.2 on 2024-06-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_attendance_recurring_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
