# Generated by Django 5.0.2 on 2024-06-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0039_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.billing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
    ]
